### ISSUE TITLE
Create a Scramble button

### ISSUE THREAD

**Issue by lymacasm** [lymacasm/Rubik-s-Cube#15]
Create a button that when clicked, will randomize the Rubik's Cube.

**Comment by batesandy123** [comment]
@lymacasm there is a pull request for this issue https://github.com/lymacasm/Rubik-s-Cube/pull/18. Checkout and improve whenever ready

**Comment by batesandy123** [comment]
jQuery library merged

**Comment by batesandy123** [comment]
Mistake, should remain closed as master has been caught up
