### ISSUE TITLE
Add a class that assumes any face is front

### ISSUE THREAD

**Issue by lymacasm** [lymacasm/Rubik-s-Cube#16]
Add a Face class that initializes itself with a face index. It will then assign itself rotation directions depending on the face index, assuming the face is front. Example:

face index : 0
self.Upper = rotate.upper
self.Down = rotate.down
self.Left  = rotate.back
self.Right = rotate.front
self.Front = rotate.left
self.Back = rotate.right

**Comment by batesandy123** [comment]
This is a good idea
